services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  user-db:
    image: mongo:7
    container_name: user-db
    ports:
      - "27017:27017"
    volumes:
      - user_db_data:/data/db

  order-db:
    image: mongo:7
    container_name: order-db
    ports:
      - "27018:27017"
    volumes:
      - order_db_data:/data/db

  notification-db:
    image: mongo:7
    container_name: notification-db
    ports:
      - "27019:27017"
    volumes:
      - notification_db_data:/data/db

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    depends_on:
      - user-db
    ports:
      - "3001:3001"

  order-service:
    build:
      context: ./order-service
    container_name: order-service
    depends_on:
      - order-db
      - rabbitmq
      - user-service
    ports:
      - "3002:3002"

  notification-service:
    build:
      context: ./notification-service
    container_name: notification-service
    depends_on:
      - notification-db
      - rabbitmq
    ports:
      - "3003:3003"

volumes:
  user_db_data:
  order_db_data:
  notification_db_data:
